---
- name: test
  debug:
    var: encrypted

- name: copy test text
  copy:
    dest: /tmp/test.txt
    content: "test test"

- name: copy encrypted text
  copy:
    dest: /tmp/test.txt
    content: "{{ encrypted }}"

- name: remove copyed file
  file:
    state: absent
    path: /tmp/test.txt
