---
- name: test
  debug:
    var: encrypted

- name: copy test text
  copy:
    dest: /tmp/test.txt
    content: "test test"

- name: copy encrypted text
  copy:
    dest: /tmp/test.txt
    content: "{{ encrypted }}"

- name: cat text
  command: cat /tmp/test.txt
  register: cat

- name: show cat text
  debug:
    var: cat.stdout

- name: remove copyed file
  file:
    state: absent
    path: /tmp/test.txt
